### PR TITLE
Naive cityhash

### LINKED ISSUE #1: Replace cityhash with `native-cityhash`
https://crates.io/crates/naive-cityhash/0.1.0

cc @PsiACE

### PR DESCRIPTION
**Pull request by PsiACE**
try to intro naive-cityhash

Fixes: #1

### CODE REVIEW

**Comment by sundy-li** [comment]
Sorry, I forgot the merge update branch  into master branch.

**Comment by sundy-li** [comment]
```
---- test_insert_decimal stdout ----
Error: Driver(BadHash)
thread 'test_insert_decimal' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/test/src/lib.rs:195:5

```

somethings related to hash.

**Comment by PsiACE** [comment]
> ```
> ---- test_insert_decimal stdout ----
> Error: Driver(BadHash)
> thread 'test_insert_decimal' panicked at 'assertion failed: `(left == right)`
>   left: `1`,
>  right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/test/src/lib.rs:195:5
> ```
> 
> somethings related to hash.

Yes, I am trying to fix this

**Comment by PsiACE** [comment]
Now, everything is ready. cc @sundy-li

**Comment by sundy-li** [comment]
Great!

**Pull request merged**
